### ISSUE TITLE
Netlify Deploy failed

### ISSUE THREAD

**Issue by paulwaldmann** [indigotree/atlas#60]
```6:37:52 AM: Build ready to start
6:37:54 AM: build-image version: 12783d4d177a66bec5a23ad1097ea7bd02931128
6:37:54 AM: buildbot version: 5a64b5cb0ce1ed3ba485935522483a4d39e15107
6:37:54 AM: Fetching cached dependencies
6:37:54 AM: Starting to download cache of 254.8KB
6:37:54 AM: Finished downloading cache in 124.544072ms
6:37:54 AM: Starting to extract cache
6:37:54 AM: Failed to fetch cache, continuing with build
6:37:54 AM: Starting to prepare the repo for build
6:37:54 AM: No cached dependencies found. Cloning fresh repo
6:37:54 AM: git clone https://github.com/indigotree/atlas
6:37:55 AM: Preparing Git Reference refs/heads/master
6:37:56 AM: Found netlify.toml. Overriding site configuration
6:37:56 AM: Different functions path detected, going to use the one specified in the toml file: 'functions' versus '' in the site
6:37:56 AM: Starting build script
6:37:56 AM: Installing dependencies
6:37:57 AM: Downloading and installing node v8.14.0...
6:37:57 AM: Downloading https://nodejs.org/dist/v8.14.0/node-v8.14.0-linux-x64.tar.xz...
6:37:57 AM: 
#
6:37:57 AM:    1.6%
6:37:57 AM: 
##################################
6:37:57 AM:                               47.9%
6:37:57 AM: 
########################################################################
6:37:57 AM: 100.0%
6:37:57 AM: Computing checksum with sha256sum
6:37:57 AM: Checksums matched!
6:38:00 AM: Now using node v8.14.0 (npm v6.4.1)
6:38:00 AM: Attempting ruby version 2.3.6, read from environment
6:38:01 AM: Using ruby version 2.3.6
6:38:01 AM: Using PHP version 5.6
6:38:01 AM: Started restoring cached node modules
6:38:01 AM: Finished restoring cached node modules
6:38:02 AM: Installing NPM modules using NPM version 6.4.1
6:38:05 AM: npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
6:38:07 AM: npm WARN
6:38:07 AM: deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
6:38:09 AM: npm WARN deprecated
6:38:09 AM:  graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
6:38:11 AM: npm
6:38:11 AM: WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
6:38:12 AM: npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
6:38:19 AM: npm
6:38:19 AM:  WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
6:38:19 AM: npm
6:38:19 AM: WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
6:38:21 AM: npm WARN
6:38:21 AM:  deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
6:38:59 AM: > node-sass@4.10.0 install /opt/build/repo/node_modules/node-sass
6:39:00 AM: > node scripts/install.js
6:39:00 AM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-57_binding.node
6:39:01 AM: Download complete
6:39:01 AM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-57/binding.node
6:39:01 AM: Caching binary to /opt/buildhome/.npm/node-sass/4.10.0/linux-x64-57_binding.node
6:39:02 AM: > uglifyjs-webpack-plugin@0.4.6 postinstall /opt/build/repo/node_modules/uglifyjs-webpack-plugin
6:39:02 AM: > node lib/post_install.js
6:39:02 AM: > node-sass@4.10.0 postinstall /opt/build/repo/node_modules/node-sass
6:39:02 AM: > node scripts/build.js
6:39:02 AM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-57/binding.node
6:39:02 AM: Testing binary
6:39:03 AM: Binary is fine
6:39:03 AM: > gifsicle@3.0.4 postinstall /opt/build/repo/node_modules/gifsicle
6:39:03 AM: > node lib/install.js
6:39:03 AM:   ✔ gifsicle pre-build test passed successfully
6:39:03 AM: > jpegtran-bin@3.2.0 postinstall /opt/build/repo/node_modules/jpegtran-bin
6:39:03 AM: > node lib/install.js
6:39:04 AM:   ✔ jpegtran pre-build test passed successfully
6:39:04 AM: > optipng-bin@3.1.4 postinstall /opt/build/repo/node_modules/optipng-bin
6:39:04 AM: > node lib/install.js
6:39:05 AM:   ✔ optipng pre-build test passed successfully
6:39:08 AM: npm notice created a lockfile as package-lock.json. You should commit this file.
6:39:08 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
6:39:08 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6:39:08 AM: added 1633 packages from 835 contributors and audited 22322 packages in 65.61s
6:39:08 AM: found 11 vulnerabilities (1 low, 6 moderate, 4 high)
6:39:08 AM:   run `npm audit fix` to fix them, or `npm audit` for details
6:39:08 AM: NPM modules installed
6:39:09 AM: Installing Hugo 0.47.1
6:39:11 AM: Started restoring cached go cache
6:39:11 AM: Finished restoring cached go cache
6:39:11 AM: unset GOOS;
6:39:11 AM: unset GOARCH;
6:39:11 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
6:39:11 AM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
6:39:11 AM: go version >&2;
6:39:11 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
6:39:11 AM: go version go1.10 linux/amd64
6:39:11 AM: Installing missing commands
6:39:11 AM: Verify run directory
6:39:11 AM: Executing user command: npm run build
6:39:11 AM: > atlas@ build /opt/build/repo
6:39:11 AM: > gulp build
6:39:11 AM: [22:39:11]
6:39:12 AM: Requiring external module @babel/register
6:39:12 AM: module.js:550
6:39:12 AM:     throw err;
6:39:12 AM:     ^
6:39:12 AM: Error: Cannot find module 'del'
6:39:12 AM:     at Function.Module._resolveFilename (module.js:548:15)
6:39:12 AM:     at Function.Module._load (module.js:475:25)
6:39:12 AM:     at Module.require (module.js:597:17)
6:39:12 AM:     at require (internal/module.js:11:18)
6:39:12 AM:     at Object.<anonymous> (/opt/build/repo/gulpfile.babel.js:4:1)
6:39:12 AM:     at Module._compile (module.js:653:30)
6:39:12 AM:     at Module._compile (/opt/build/repo/node_modules/pirates/lib/index.js:83:24)
6:39:12 AM:     at Module._extensions..js (module.js:664:10)
6:39:12 AM:     at Object.newLoader [as .js] (/opt/build/repo/node_modules/pirates/lib/index.js:88:7)
6:39:12 AM:     at Module.load (module.js:566:32)
6:39:12 AM: npm ERR! code ELIFECYCLE
6:39:12 AM: npm ERR! errno 1
6:39:12 AM: npm ERR! atlas@ build: `gulp build`
6:39:12 AM: npm ERR! Exit status 1
6:39:12 AM: npm ERR!
6:39:12 AM: npm ERR! Failed at the atlas@ build script.
6:39:12 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
6:39:13 AM: npm ERR! A complete log of this run can be found in:
6:39:13 AM: npm ERR!     /opt/buildhome/.npm/_logs/2018-11-30T22_39_12_665Z-debug.log
6:39:13 AM: Caching artifacts
6:39:13 AM: Started saving node modules
6:39:13 AM: Finished saving node modules
6:39:13 AM: Started saving pip cache
6:39:13 AM: Finished saving pip cache
6:39:13 AM: Started saving emacs cask dependencies
6:39:13 AM: Finished saving emacs cask dependencies
6:39:13 AM: Started saving maven dependencies
6:39:13 AM: Finished saving maven dependencies
6:39:13 AM: Started saving boot dependencies
6:39:13 AM: Finished saving boot dependencies
6:39:13 AM: Started saving go dependencies
6:39:13 AM: Finished saving go dependencies
6:39:13 AM: Cached node version v8.14.0
6:39:13 AM: Error running command: Build script returned non-zero exit code: 1
6:39:13 AM: Failing build: Failed to build site
6:39:13 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
6:39:13 AM: Finished processing build request in 1m19.307979546s```

**Comment by crgeary** [comment]
Ooohh, were missing the `del` package. Not sure how that's happened.

Try: `npm install del --save`

I will update Atlas as soon as I'm infront of a computer. Thanks for raising this.

**Comment by paulwaldmann** [comment]
I should have probably mentioned, that the log is coming directly from Netlify.
